// Generated country list constant. Do not edit manually.
import 'package:gajacash_sample/features/onboarding/phone_entry_controller.dart';

class CountryData {
  static const List<Country> countries = [
    Country(name: 'Afghanistan', code: '+93', flagAsset: 'https://flagcdn.com/w40/af.png'),
    Country(name: 'Albania', code: '+355', flagAsset: 'https://flagcdn.com/w40/al.png'),
    Country(name: 'Algeria', code: '+213', flagAsset: 'https://flagcdn.com/w40/dz.png'),
    Country(name: 'Andorra', code: '+376', flagAsset: 'https://flagcdn.com/w40/ad.png'),
    Country(name: 'Angola', code: '+244', flagAsset: 'https://flagcdn.com/w40/ao.png'),
    Country(name: 'Anguilla', code: '+1 264', flagAsset: 'https://flagcdn.com/w40/ai.png'),
    Country(name: 'Antigua and Barbuda', code: '+1268', flagAsset: 'https://flagcdn.com/w40/ag.png'),
    Country(name: 'Argentina', code: '+54', flagAsset: 'https://flagcdn.com/w40/ar.png'),
    Country(name: 'Armenia', code: '+374', flagAsset: 'https://flagcdn.com/w40/am.png'),
    Country(name: 'Aruba', code: '+297', flagAsset: 'https://flagcdn.com/w40/aw.png'),
    Country(name: 'Australia', code: '+61', flagAsset: 'https://flagcdn.com/w40/au.png'),
    Country(name: 'Austria', code: '+43', flagAsset: 'https://flagcdn.com/w40/at.png'),
    Country(name: 'Azerbaijan', code: '+994', flagAsset: 'https://flagcdn.com/w40/az.png'),
    Country(name: 'Bahrain', code: '+973', flagAsset: 'https://flagcdn.com/w40/bh.png'),
    Country(name: 'Bangladesh', code: '+880', flagAsset: 'https://flagcdn.com/w40/bd.png'),
    Country(name: 'Barbados', code: '+1 246', flagAsset: 'https://flagcdn.com/w40/bb.png'),
    Country(name: 'Belarus', code: '+375', flagAsset: 'https://flagcdn.com/w40/by.png'),
    Country(name: 'Belgium', code: '+32', flagAsset: 'https://flagcdn.com/w40/be.png'),
    Country(name: 'Belize', code: '+501', flagAsset: 'https://flagcdn.com/w40/bz.png'),
    Country(name: 'Benin', code: '+229', flagAsset: 'https://flagcdn.com/w40/bj.png'),
    Country(name: 'Bermuda', code: '+1 441', flagAsset: 'https://flagcdn.com/w40/bm.png'),
    Country(name: 'Bhutan', code: '+975', flagAsset: 'https://flagcdn.com/w40/bt.png'),
    Country(name: 'Bosnia and Herzegovina', code: '+387', flagAsset: 'https://flagcdn.com/w40/ba.png'),
    Country(name: 'Botswana', code: '+267', flagAsset: 'https://flagcdn.com/w40/bw.png'),
    Country(name: 'Brazil', code: '+55', flagAsset: 'https://flagcdn.com/w40/br.png'),
    Country(name: 'British Indian Ocean Territory', code: '+246', flagAsset: 'https://flagcdn.com/w40/io.png'),
    Country(name: 'Bulgaria', code: '+359', flagAsset: 'https://flagcdn.com/w40/bg.png'),
    Country(name: 'Burkina Faso', code: '+226', flagAsset: 'https://flagcdn.com/w40/bf.png'),
    Country(name: 'Burundi', code: '+257', flagAsset: 'https://flagcdn.com/w40/bi.png'),
    Country(name: 'Cambodia', code: '+855', flagAsset: 'https://flagcdn.com/w40/kh.png'),
    Country(name: 'Cameroon', code: '+237', flagAsset: 'https://flagcdn.com/w40/cm.png'),
    Country(name: 'Canada', code: '+1', flagAsset: 'https://flagcdn.com/w40/ca.png'),
    Country(name: 'Cape Verde', code: '+238', flagAsset: 'https://flagcdn.com/w40/cv.png'),
    Country(name: 'Cayman Islands', code: '+ 345', flagAsset: 'https://flagcdn.com/w40/ky.png'),
    Country(name: 'Central African Republic', code: '+236', flagAsset: 'https://flagcdn.com/w40/cf.png'),
    Country(name: 'Chad', code: '+235', flagAsset: 'https://flagcdn.com/w40/td.png'),
    Country(name: 'Chile', code: '+56', flagAsset: 'https://flagcdn.com/w40/cl.png'),
    Country(name: 'China', code: '+86', flagAsset: 'https://flagcdn.com/w40/cn.png'),
    Country(name: 'Christmas Island', code: '+61', flagAsset: 'https://flagcdn.com/w40/cx.png'),
    Country(name: 'Cocos (Keeling) Islands', code: '+61', flagAsset: 'https://flagcdn.com/w40/cc.png'),
    Country(name: 'Colombia', code: '+57', flagAsset: 'https://flagcdn.com/w40/co.png'),
    Country(name: 'Comoros', code: '+269', flagAsset: 'https://flagcdn.com/w40/km.png'),
    Country(name: 'Cook Islands', code: '+682', flagAsset: 'https://flagcdn.com/w40/ck.png'),
    Country(name: 'Costa Rica', code: '+506', flagAsset: 'https://flagcdn.com/w40/cr.png'),
    Country(name: 'Croatia', code: '+385', flagAsset: 'https://flagcdn.com/w40/hr.png'),
    Country(name: 'Cuba', code: '+53', flagAsset: 'https://flagcdn.com/w40/cu.png'),
    Country(name: 'Cyprus', code: '+537', flagAsset: 'https://flagcdn.com/w40/cy.png'),
    Country(name: 'Czech Republic', code: '+420', flagAsset: 'https://flagcdn.com/w40/cz.png'),
    Country(name: 'Denmark', code: '+45', flagAsset: 'https://flagcdn.com/w40/dk.png'),
    Country(name: 'Djibouti', code: '+253', flagAsset: 'https://flagcdn.com/w40/dj.png'),
    Country(name: 'Dominica', code: '+1 767', flagAsset: 'https://flagcdn.com/w40/dm.png'),
    Country(name: 'Dominican Republic', code: '+1 849', flagAsset: 'https://flagcdn.com/w40/do.png'),
    Country(name: 'Ecuador', code: '+593', flagAsset: 'https://flagcdn.com/w40/ec.png'),
    Country(name: 'Egypt', code: '+20', flagAsset: 'https://flagcdn.com/w40/eg.png'),
    Country(name: 'El Salvador', code: '+503', flagAsset: 'https://flagcdn.com/w40/sv.png'),
    Country(name: 'Equatorial Guinea', code: '+240', flagAsset: 'https://flagcdn.com/w40/gq.png'),
    Country(name: 'Eritrea', code: '+291', flagAsset: 'https://flagcdn.com/w40/er.png'),
    Country(name: 'Estonia', code: '+372', flagAsset: 'https://flagcdn.com/w40/ee.png'),
    Country(name: 'Ethiopia', code: '+251', flagAsset: 'https://flagcdn.com/w40/et.png'),
    Country(name: 'Faroe Islands', code: '+298', flagAsset: 'https://flagcdn.com/w40/fo.png'),
    Country(name: 'Fiji', code: '+679', flagAsset: 'https://flagcdn.com/w40/fj.png'),
    Country(name: 'Finland', code: '+358', flagAsset: 'https://flagcdn.com/w40/fi.png'),
    Country(name: 'France', code: '+33', flagAsset: 'https://flagcdn.com/w40/fr.png'),
    Country(name: 'French Guiana', code: '+594', flagAsset: 'https://flagcdn.com/w40/gf.png'),
    Country(name: 'French Polynesia', code: '+689', flagAsset: 'https://flagcdn.com/w40/pf.png'),
    Country(name: 'Gabon', code: '+241', flagAsset: 'https://flagcdn.com/w40/ga.png'),
    Country(name: 'Georgia', code: '+995', flagAsset: 'https://flagcdn.com/w40/ge.png'),
    Country(name: 'Germany', code: '+49', flagAsset: 'https://flagcdn.com/w40/de.png'),
    Country(name: 'Ghana', code: '+233', flagAsset: 'https://flagcdn.com/w40/gh.png'),
    Country(name: 'Gibraltar', code: '+350', flagAsset: 'https://flagcdn.com/w40/gi.png'),
    Country(name: 'Greece', code: '+30', flagAsset: 'https://flagcdn.com/w40/gr.png'),
    Country(name: 'Greenland', code: '+299', flagAsset: 'https://flagcdn.com/w40/gl.png'),
    Country(name: 'Grenada', code: '+1 473', flagAsset: 'https://flagcdn.com/w40/gd.png'),
    Country(name: 'Guadeloupe', code: '+590', flagAsset: 'https://flagcdn.com/w40/gp.png'),
    Country(name: 'Guam', code: '+1 671', flagAsset: 'https://flagcdn.com/w40/gu.png'),
    Country(name: 'Guatemala', code: '+502', flagAsset: 'https://flagcdn.com/w40/gt.png'),
    Country(name: 'Guernsey', code: '+44', flagAsset: 'https://flagcdn.com/w40/gg.png'),
    Country(name: 'Guinea', code: '+224', flagAsset: 'https://flagcdn.com/w40/gn.png'),
    Country(name: 'Guinea-Bissau', code: '+245', flagAsset: 'https://flagcdn.com/w40/gw.png'),
    Country(name: 'Guyana', code: '+595', flagAsset: 'https://flagcdn.com/w40/gy.png'),
    Country(name: 'Haiti', code: '+509', flagAsset: 'https://flagcdn.com/w40/ht.png'),
    Country(name: 'Honduras', code: '+504', flagAsset: 'https://flagcdn.com/w40/hn.png'),
    Country(name: 'Hong Kong', code: '+852', flagAsset: 'https://flagcdn.com/w40/hk.png'),
    Country(name: 'Hungary', code: '+36', flagAsset: 'https://flagcdn.com/w40/hu.png'),
    Country(name: 'Iceland', code: '+354', flagAsset: 'https://flagcdn.com/w40/is.png'),
    Country(name: 'India', code: '+91', flagAsset: 'https://flagcdn.com/w40/in.png'),
    Country(name: 'Indonesia', code: '+62', flagAsset: 'https://flagcdn.com/w40/id.png'),
    Country(name: 'Iraq', code: '+964', flagAsset: 'https://flagcdn.com/w40/iq.png'),
    Country(name: 'Isle of Man', code: '+44', flagAsset: 'https://flagcdn.com/w40/im.png'),
    Country(name: 'Israel', code: '+972', flagAsset: 'https://flagcdn.com/w40/il.png'),
    Country(name: 'Italy', code: '+39', flagAsset: 'https://flagcdn.com/w40/it.png'),
    Country(name: 'Jamaica', code: '+1 876', flagAsset: 'https://flagcdn.com/w40/jm.png'),
    Country(name: 'Japan', code: '+81', flagAsset: 'https://flagcdn.com/w40/jp.png'),
    Country(name: 'Jersey', code: '+44', flagAsset: 'https://flagcdn.com/w40/je.png'),
    Country(name: 'Jordan', code: '+962', flagAsset: 'https://flagcdn.com/w40/jo.png'),
    Country(name: 'Kazakhstan', code: '+7 7', flagAsset: 'https://flagcdn.com/w40/kz.png'),
    Country(name: 'Kenya', code: '+254', flagAsset: 'https://flagcdn.com/w40/ke.png'),
    Country(name: 'Kiribati', code: '+686', flagAsset: 'https://flagcdn.com/w40/ki.png'),
    Country(name: 'Kuwait', code: '+965', flagAsset: 'https://flagcdn.com/w40/kw.png'),
    Country(name: 'Kyrgyzstan', code: '+996', flagAsset: 'https://flagcdn.com/w40/kg.png'),
    Country(name: 'Latvia', code: '+371', flagAsset: 'https://flagcdn.com/w40/lv.png'),
    Country(name: 'Lebanon', code: '+961', flagAsset: 'https://flagcdn.com/w40/lb.png'),
    Country(name: 'Lesotho', code: '+266', flagAsset: 'https://flagcdn.com/w40/ls.png'),
    Country(name: 'Liberia', code: '+231', flagAsset: 'https://flagcdn.com/w40/lr.png'),
    Country(name: 'Liechtenstein', code: '+423', flagAsset: 'https://flagcdn.com/w40/li.png'),
    Country(name: 'Lithuania', code: '+370', flagAsset: 'https://flagcdn.com/w40/lt.png'),
    Country(name: 'Luxembourg', code: '+352', flagAsset: 'https://flagcdn.com/w40/lu.png'),
    Country(name: 'Madagascar', code: '+261', flagAsset: 'https://flagcdn.com/w40/mg.png'),
    Country(name: 'Malawi', code: '+265', flagAsset: 'https://flagcdn.com/w40/mw.png'),
    Country(name: 'Malaysia', code: '+60', flagAsset: 'https://flagcdn.com/w40/my.png'),
    Country(name: 'Maldives', code: '+960', flagAsset: 'https://flagcdn.com/w40/mv.png'),
    Country(name: 'Mali', code: '+223', flagAsset: 'https://flagcdn.com/w40/ml.png'),
    Country(name: 'Malta', code: '+356', flagAsset: 'https://flagcdn.com/w40/mt.png'),
    Country(name: 'Marshall Islands', code: '+692', flagAsset: 'https://flagcdn.com/w40/mh.png'),
    Country(name: 'Martinique', code: '+596', flagAsset: 'https://flagcdn.com/w40/mq.png'),
    Country(name: 'Mauritania', code: '+222', flagAsset: 'https://flagcdn.com/w40/mr.png'),
    Country(name: 'Mauritius', code: '+230', flagAsset: 'https://flagcdn.com/w40/mu.png'),
    Country(name: 'Mayotte', code: '+262', flagAsset: 'https://flagcdn.com/w40/yt.png'),
    Country(name: 'Mexico', code: '+52', flagAsset: 'https://flagcdn.com/w40/mx.png'),
    Country(name: 'Monaco', code: '+377', flagAsset: 'https://flagcdn.com/w40/mc.png'),
    Country(name: 'Mongolia', code: '+976', flagAsset: 'https://flagcdn.com/w40/mn.png'),
    Country(name: 'Montenegro', code: '+382', flagAsset: 'https://flagcdn.com/w40/me.png'),
    Country(name: 'Montserrat', code: '+1664', flagAsset: 'https://flagcdn.com/w40/ms.png'),
    Country(name: 'Morocco', code: '+212', flagAsset: 'https://flagcdn.com/w40/ma.png'),
    Country(name: 'Mozambique', code: '+258', flagAsset: 'https://flagcdn.com/w40/mz.png'),
    Country(name: 'Myanmar', code: '+95', flagAsset: 'https://flagcdn.com/w40/mm.png'),
    Country(name: 'Namibia', code: '+264', flagAsset: 'https://flagcdn.com/w40/na.png'),
    Country(name: 'Nauru', code: '+674', flagAsset: 'https://flagcdn.com/w40/nr.png'),
    Country(name: 'Nepal', code: '+977', flagAsset: 'https://flagcdn.com/w40/np.png'),
    Country(name: 'Netherlands', code: '+31', flagAsset: 'https://flagcdn.com/w40/nl.png'),
    Country(name: 'New Caledonia', code: '+687', flagAsset: 'https://flagcdn.com/w40/nc.png'),
    Country(name: 'New Zealand', code: '+64', flagAsset: 'https://flagcdn.com/w40/nz.png'),
    Country(name: 'Nicaragua', code: '+505', flagAsset: 'https://flagcdn.com/w40/ni.png'),
    Country(name: 'Niger', code: '+227', flagAsset: 'https://flagcdn.com/w40/ne.png'),
    Country(name: 'Nigeria', code: '+234', flagAsset: 'https://flagcdn.com/w40/ng.png'),
    Country(name: 'Niue', code: '+683', flagAsset: 'https://flagcdn.com/w40/nu.png'),
    Country(name: 'Norfolk Island', code: '+672', flagAsset: 'https://flagcdn.com/w40/nf.png'),
    Country(name: 'Northern Mariana Islands', code: '+1 670', flagAsset: 'https://flagcdn.com/w40/mp.png'),
    Country(name: 'Norway', code: '+47', flagAsset: 'https://flagcdn.com/w40/no.png'),
    Country(name: 'Oman', code: '+968', flagAsset: 'https://flagcdn.com/w40/om.png'),
    Country(name: 'Pakistan', code: '+92', flagAsset: 'https://flagcdn.com/w40/pk.png'),
    Country(name: 'Palau', code: '+680', flagAsset: 'https://flagcdn.com/w40/pw.png'),
    Country(name: 'Panama', code: '+507', flagAsset: 'https://flagcdn.com/w40/pa.png'),
    Country(name: 'Papua New Guinea', code: '+675', flagAsset: 'https://flagcdn.com/w40/pg.png'),
    Country(name: 'Paraguay', code: '+595', flagAsset: 'https://flagcdn.com/w40/py.png'),
    Country(name: 'Peru', code: '+51', flagAsset: 'https://flagcdn.com/w40/pe.png'),
    Country(name: 'Philippines', code: '+63', flagAsset: 'https://flagcdn.com/w40/ph.png'),
    Country(name: 'Poland', code: '+48', flagAsset: 'https://flagcdn.com/w40/pl.png'),
    Country(name: 'Portugal', code: '+351', flagAsset: 'https://flagcdn.com/w40/pt.png'),
    Country(name: 'Puerto Rico', code: '+1 939', flagAsset: 'https://flagcdn.com/w40/pr.png'),
    Country(name: 'Qatar', code: '+974', flagAsset: 'https://flagcdn.com/w40/qa.png'),
    Country(name: 'Romania', code: '+40', flagAsset: 'https://flagcdn.com/w40/ro.png'),
    Country(name: 'Russia', code: '+7', flagAsset: 'https://flagcdn.com/w40/ru.png'),
    Country(name: 'Rwanda', code: '+250', flagAsset: 'https://flagcdn.com/w40/rw.png'),
    Country(name: 'Réunion', code: '+262', flagAsset: 'https://flagcdn.com/w40/re.png'),
    Country(name: 'Saint Barthélemy', code: '+590', flagAsset: 'https://flagcdn.com/w40/bl.png'),
    Country(name: 'Saint Kitts and Nevis', code: '+1 869', flagAsset: 'https://flagcdn.com/w40/kn.png'),
    Country(name: 'Saint Lucia', code: '+1 758', flagAsset: 'https://flagcdn.com/w40/lc.png'),
    Country(name: 'Saint Martin', code: '+590', flagAsset: 'https://flagcdn.com/w40/mf.png'),
    Country(name: 'Saint Pierre and Miquelon', code: '+508', flagAsset: 'https://flagcdn.com/w40/pm.png'),
    Country(name: 'Saint Vincent and the Grenadines', code: '+1 784', flagAsset: 'https://flagcdn.com/w40/vc.png'),
    Country(name: 'Samoa', code: '+685', flagAsset: 'https://flagcdn.com/w40/ws.png'),
    Country(name: 'San Marino', code: '+378', flagAsset: 'https://flagcdn.com/w40/sm.png'),
    Country(name: 'Saudi Arabia', code: '+966', flagAsset: 'https://flagcdn.com/w40/sa.png'),
    Country(name: 'Senegal', code: '+221', flagAsset: 'https://flagcdn.com/w40/sn.png'),
    Country(name: 'Serbia', code: '+381', flagAsset: 'https://flagcdn.com/w40/rs.png'),
    Country(name: 'Seychelles', code: '+248', flagAsset: 'https://flagcdn.com/w40/sc.png'),
    Country(name: 'Sierra Leone', code: '+232', flagAsset: 'https://flagcdn.com/w40/sl.png'),
    Country(name: 'Singapore', code: '+65', flagAsset: 'https://flagcdn.com/w40/sg.png'),
    Country(name: 'Slovakia', code: '+421', flagAsset: 'https://flagcdn.com/w40/sk.png'),
    Country(name: 'Slovenia', code: '+386', flagAsset: 'https://flagcdn.com/w40/si.png'),
    Country(name: 'Solomon Islands', code: '+677', flagAsset: 'https://flagcdn.com/w40/sb.png'),
    Country(name: 'Somalia', code: '+252', flagAsset: 'https://flagcdn.com/w40/so.png'),
    Country(name: 'South Africa', code: '+27', flagAsset: 'https://flagcdn.com/w40/za.png'),
    Country(name: 'Spain', code: '+34', flagAsset: 'https://flagcdn.com/w40/es.png'),
    Country(name: 'Sri Lanka', code: '+94', flagAsset: 'https://flagcdn.com/w40/lk.png'),
    Country(name: 'Sudan', code: '+249', flagAsset: 'https://flagcdn.com/w40/sd.png'),
    Country(name: 'Suriname', code: '+597', flagAsset: 'https://flagcdn.com/w40/sr.png'),
    Country(name: 'Svalbard and Jan Mayen', code: '+47', flagAsset: 'https://flagcdn.com/w40/sj.png'),
    Country(name: 'Swaziland', code: '+268', flagAsset: 'https://flagcdn.com/w40/sz.png'),
    Country(name: 'Sweden', code: '+46', flagAsset: 'https://flagcdn.com/w40/se.png'),
    Country(name: 'Switzerland', code: '+41', flagAsset: 'https://flagcdn.com/w40/ch.png'),
    Country(name: 'Tajikistan', code: '+992', flagAsset: 'https://flagcdn.com/w40/tj.png'),
    Country(name: 'Thailand', code: '+66', flagAsset: 'https://flagcdn.com/w40/th.png'),
    Country(name: 'Togo', code: '+228', flagAsset: 'https://flagcdn.com/w40/tg.png'),
    Country(name: 'Tokelau', code: '+690', flagAsset: 'https://flagcdn.com/w40/tk.png'),
    Country(name: 'Tonga', code: '+676', flagAsset: 'https://flagcdn.com/w40/to.png'),
    Country(name: 'Trinidad and Tobago', code: '+1 868', flagAsset: 'https://flagcdn.com/w40/tt.png'),
    Country(name: 'Tunisia', code: '+216', flagAsset: 'https://flagcdn.com/w40/tn.png'),
    Country(name: 'Turkey', code: '+90', flagAsset: 'https://flagcdn.com/w40/tr.png'),
    Country(name: 'Turkmenistan', code: '+993', flagAsset: 'https://flagcdn.com/w40/tm.png'),
    Country(name: 'Turks and Caicos Islands', code: '+1 649', flagAsset: 'https://flagcdn.com/w40/tc.png'),
    Country(name: 'Tuvalu', code: '+688', flagAsset: 'https://flagcdn.com/w40/tv.png'),
    Country(name: 'Uganda', code: '+256', flagAsset: 'https://flagcdn.com/w40/ug.png'),
    Country(name: 'Ukraine', code: '+380', flagAsset: 'https://flagcdn.com/w40/ua.png'),
    Country(name: 'United Arab Emirates', code: '+971', flagAsset: 'https://flagcdn.com/w40/ae.png'),
    Country(name: 'United Kingdom', code: '+44', flagAsset: 'https://flagcdn.com/w40/gb.png'),
    Country(name: 'United States', code: '+1', flagAsset: 'https://flagcdn.com/w40/us.png'),
    Country(name: 'Uruguay', code: '+598', flagAsset: 'https://flagcdn.com/w40/uy.png'),
    Country(name: 'Uzbekistan', code: '+998', flagAsset: 'https://flagcdn.com/w40/uz.png'),
    Country(name: 'Vanuatu', code: '+678', flagAsset: 'https://flagcdn.com/w40/vu.png'),
    Country(name: 'Wallis and Futuna', code: '+681', flagAsset: 'https://flagcdn.com/w40/wf.png'),
    Country(name: 'Yemen', code: '+967', flagAsset: 'https://flagcdn.com/w40/ye.png'),
    Country(name: 'Zambia', code: '+260', flagAsset: 'https://flagcdn.com/w40/zm.png'),
    Country(name: 'Zimbabwe', code: '+263', flagAsset: 'https://flagcdn.com/w40/zw.png'),
  ];
}
